#!/bin/sh


#make variable to represent speaker or headphone 
#
#test this variable with sed statement 

test= amixer get Speaker | sed -n 's/^.*\[\([0-9]\+%\).*$/\1/p' | uniq 
input="Speaker"

if [$test == "on"];
then 
	input="it worked"
	echo "$input"
fi
